In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [35]:
dataset = pd.read_csv('/content/heart.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [36]:

y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [37]:
dataset

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[303 rows x 14 columns]

In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [39]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 5)
x_train = lda.fit_transform(x_train, y_train)
x_test = lda.transform(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:463: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(13, 2 - 1) = 1 components.
  ChangedBehaviorWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:469: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)


In [40]:
x_train

array([[ 2.28011405],
       [ 1.29304306],
       [ 1.12713495],
       [ 0.45231235],
       [ 0.28104698],
       [ 0.63916824],
       [-0.81006589],
       [ 0.48696886],
       [ 0.04366996],
       [-0.14953291],
       [ 1.5049131 ],
       [ 0.84960769],
       [-1.81132694],
       [-1.51403343],
       [ 0.99669867],
       [-0.71278735],
       [ 0.18157756],
       [ 0.43479033],
       [-0.56806004],
       [-2.62752948],
       [-2.20255228],
       [-1.21891673],
       [-0.28413088],
       [-1.55266416],
       [-0.04791851],
       [-1.8303197 ],
       [ 0.30559855],
       [ 0.47568052],
       [-0.90596443],
       [-1.7289081 ],
       [ 0.48302242],
       [ 0.30645275],
       [-1.82322632],
       [ 1.42009274],
       [-1.85343048],
       [-1.60408934],
       [-2.085508  ],
       [ 1.57858834],
       [-1.66249246],
       [-1.5990848 ],
       [ 2.25028304],
       [-2.50199764],
       [ 0.15023526],
       [-0.95577282],
       [ 1.01709404],
       [ 1

In [41]:
from sklearn.linear_model import LogisticRegression
classifier1 = LogisticRegression(random_state = 0)
classifier1.fit(x_train, y_train)
y_pred1=classifier1.predict(x_test)

In [42]:
from sklearn.neighbors import KNeighborsClassifier
classifier2 = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2)
classifier2.fit(x_train, y_train)
y_pred2=classifier2.predict(x_test)

In [43]:
from sklearn.svm import SVC
classifier3 = SVC(kernel = 'linear', random_state = 0)
classifier3.fit(x_train, y_train)
y_pred3=classifier3.predict(x_test)

In [44]:
from sklearn.naive_bayes import GaussianNB
classifier4=GaussianNB()
classifier4.fit(x_train, y_train)
y_pred4=classifier4.predict(x_test)

In [45]:
from sklearn.tree import DecisionTreeClassifier
classifier5 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier5.fit(x_train, y_train)
y_pred5=classifier5.predict(x_test)

In [46]:
from sklearn.ensemble import RandomForestClassifier
classifier6 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier6.fit(x_train, y_train)
y_pred6=classifier6.predict(x_test)

In [47]:
from sklearn.linear_model import  SGDClassifier
classifier7 =  SGDClassifier(random_state=42)
classifier7.fit(x_train, y_train) 
y_pred7 = classifier7.predict(x_test)

In [48]:
from sklearn.linear_model import PassiveAggressiveClassifier
classifier8 = PassiveAggressiveClassifier()
classifier8.fit(x_train, y_train)
y_pred8=classifier8.predict(x_test)

In [49]:
from sklearn.ensemble import AdaBoostClassifier
classifier9 = AdaBoostClassifier(n_estimators=100, random_state=0)
classifier9.fit(x_train, y_train)
y_pred9=classifier9.predict(x_test)

In [50]:
from sklearn.ensemble import VotingClassifier
classifier10 = VotingClassifier(estimators=[('lr', classifier1), ('knn', classifier2), ('svc', classifier3)], voting='hard')
classifier10.fit(x_train, y_train)
y_pred10 = classifier10.predict(x_test)

In [51]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred1)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred1))
print(f1_score(y_test, y_pred1,average='macro'))
print(precision_score(y_test,y_pred1,average='macro'))
print(recall_score(y_test,y_pred1,average='macro'))
print(balanced_accuracy_score(y_test,y_pred1))
print(classification_report(y_test, y_pred1))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred1,average='macro'))

[[21  6]
 [ 4 30]]
0.8360655737704918
0.8324175824175823
0.8366666666666667
0.8300653594771241
0.8300653594771241
              precision    recall  f1-score   support

           0       0.84      0.78      0.81        27
           1       0.83      0.88      0.86        34

    accuracy                           0.84        61
   macro avg       0.84      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61

0.8300653594771241


In [52]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred2)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred2))
print(f1_score(y_test, y_pred2,average='macro'))
print(precision_score(y_test,y_pred2,average='macro'))
print(recall_score(y_test,y_pred2,average='macro'))
print(balanced_accuracy_score(y_test,y_pred2))
print(classification_report(y_test, y_pred2))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred2,average='macro'))

[[23  4]
 [ 7 27]]
0.819672131147541
0.81889338731444
0.8188172043010753
0.8229847494553377
0.8229847494553377
              precision    recall  f1-score   support

           0       0.77      0.85      0.81        27
           1       0.87      0.79      0.83        34

    accuracy                           0.82        61
   macro avg       0.82      0.82      0.82        61
weighted avg       0.82      0.82      0.82        61

0.8229847494553376


In [53]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred3)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred3))
print(f1_score(y_test, y_pred3,average='macro'))
print(precision_score(y_test,y_pred3,average='macro'))
print(recall_score(y_test,y_pred3,average='macro'))
print(balanced_accuracy_score(y_test,y_pred3))
print(classification_report(y_test, y_pred3))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred3,average='macro'))

[[20  7]
 [ 3 31]]
0.8360655737704918
0.8305555555555555
0.8426773455377574
0.8262527233115469
0.8262527233115469
              precision    recall  f1-score   support

           0       0.87      0.74      0.80        27
           1       0.82      0.91      0.86        34

    accuracy                           0.84        61
   macro avg       0.84      0.83      0.83        61
weighted avg       0.84      0.84      0.83        61

0.8262527233115468


In [54]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred4)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred4))
print(f1_score(y_test, y_pred4,average='macro'))
print(precision_score(y_test,y_pred4,average='macro'))
print(recall_score(y_test,y_pred4,average='macro'))
print(balanced_accuracy_score(y_test,y_pred4))
print(classification_report(y_test, y_pred4))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred4,average='macro'))

[[20  7]
 [ 3 31]]
0.8360655737704918
0.8305555555555555
0.8426773455377574
0.8262527233115469
0.8262527233115469
              precision    recall  f1-score   support

           0       0.87      0.74      0.80        27
           1       0.82      0.91      0.86        34

    accuracy                           0.84        61
   macro avg       0.84      0.83      0.83        61
weighted avg       0.84      0.84      0.83        61

0.8262527233115468


In [55]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred5)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred5))
print(f1_score(y_test, y_pred5,average='macro'))
print(precision_score(y_test,y_pred5,average='macro'))
print(recall_score(y_test,y_pred5,average='macro'))
print(balanced_accuracy_score(y_test,y_pred5))
print(classification_report(y_test, y_pred5))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred5,average='macro'))

[[20  7]
 [ 7 27]]
0.7704918032786885
0.7674291938997821
0.7674291938997821
0.7674291938997821
0.7674291938997821
              precision    recall  f1-score   support

           0       0.74      0.74      0.74        27
           1       0.79      0.79      0.79        34

    accuracy                           0.77        61
   macro avg       0.77      0.77      0.77        61
weighted avg       0.77      0.77      0.77        61

0.767429193899782


In [56]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred6)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred6))
print(f1_score(y_test, y_pred6,average='macro'))
print(precision_score(y_test,y_pred6,average='macro'))
print(recall_score(y_test,y_pred6,average='macro'))
print(balanced_accuracy_score(y_test,y_pred6))
print(classification_report(y_test, y_pred6))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred6,average='macro'))

[[20  7]
 [ 7 27]]
0.7704918032786885
0.7674291938997821
0.7674291938997821
0.7674291938997821
0.7674291938997821
              precision    recall  f1-score   support

           0       0.74      0.74      0.74        27
           1       0.79      0.79      0.79        34

    accuracy                           0.77        61
   macro avg       0.77      0.77      0.77        61
weighted avg       0.77      0.77      0.77        61

0.767429193899782


In [57]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred7)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred7))
print(f1_score(y_test, y_pred7,average='macro'))
print(precision_score(y_test,y_pred7,average='macro'))
print(recall_score(y_test,y_pred7,average='macro'))
print(balanced_accuracy_score(y_test,y_pred7))
print(classification_report(y_test, y_pred7))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred7,average='macro'))

[[21  6]
 [ 4 30]]
0.8360655737704918
0.8324175824175823
0.8366666666666667
0.8300653594771241
0.8300653594771241
              precision    recall  f1-score   support

           0       0.84      0.78      0.81        27
           1       0.83      0.88      0.86        34

    accuracy                           0.84        61
   macro avg       0.84      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61

0.8300653594771241


In [58]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred8)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred8))
print(f1_score(y_test, y_pred8,average='macro'))
print(precision_score(y_test,y_pred8,average='macro'))
print(recall_score(y_test,y_pred8,average='macro'))
print(balanced_accuracy_score(y_test,y_pred8))
print(classification_report(y_test, y_pred8))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred8,average='macro'))

[[ 3 24]
 [ 0 34]]
0.6065573770491803
0.4695652173913043
0.7931034482758621
0.5555555555555556
0.5555555555555556
              precision    recall  f1-score   support

           0       1.00      0.11      0.20        27
           1       0.59      1.00      0.74        34

    accuracy                           0.61        61
   macro avg       0.79      0.56      0.47        61
weighted avg       0.77      0.61      0.50        61

0.5555555555555556


In [59]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred9)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred9))
print(f1_score(y_test, y_pred9,average='macro'))
print(precision_score(y_test,y_pred9,average='macro'))
print(recall_score(y_test,y_pred9,average='macro'))
print(balanced_accuracy_score(y_test,y_pred9))
print(classification_report(y_test, y_pred9))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred9,average='macro'))

[[24  3]
 [ 7 27]]
0.8360655737704918
0.8356681034482758
0.8370967741935484
0.8415032679738561
0.8415032679738561
              precision    recall  f1-score   support

           0       0.77      0.89      0.83        27
           1       0.90      0.79      0.84        34

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61

0.841503267973856


In [60]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred10)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred10))
print(f1_score(y_test, y_pred10,average='macro'))
print(precision_score(y_test,y_pred10,average='macro'))
print(recall_score(y_test,y_pred10,average='macro'))
print(balanced_accuracy_score(y_test,y_pred10))
print(classification_report(y_test, y_pred10))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred10,average='macro'))

[[21  6]
 [ 4 30]]
0.8360655737704918
0.8324175824175823
0.8366666666666667
0.8300653594771241
0.8300653594771241
              precision    recall  f1-score   support

           0       0.84      0.78      0.81        27
           1       0.83      0.88      0.86        34

    accuracy                           0.84        61
   macro avg       0.84      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61

0.8300653594771241
